const laptops = [
  {
    id: "laptop1",
    name: "Lenovo IdeaPad 3 Core i3 11th Gen - (8 GB/256 GB SSD/Windows 11 Home) 14ITL05 Thin and Light Laptop",
    brand: "Lenovo",
    price: 36990.0,
    ratings: 4.2,
    details:
      "['Intel Core i3 Processor (11th Gen)' '8 GB DDR4 RAM' '64 bit Windows 11 Operating System' '256 GB SSD' '35.56 cm (14 inch) Display' 'Office Home and Student 2021' '2 Year Onsite Warranty']",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUukDFoMgb2ZbfwhRRPvY3MOYXnRDbkiMCTshfv_NnA36JjbYBlp7iczoayhjmesJ-QMw&usqp=CAU",
  },
  {
    id: "laptop2",
    name: "Lenovo IdeaPad 3 Core i3 11th Gen - (8 GB/512 GB SSD/Windows 11 Home) 82H801L7IN | 82H802FJIN | 82H802",
    brand: "Lenovo",
    price: 37990.0,
    ratings: 4.2,
    details:
      "['Intel Core i3 Processor (11th Gen)' '8 GB DDR4 RAM' '64 bit Windows 11 Operating System' '512 GB SSD' '39.62 cm (15.6 inch) Display' 'Office Home and Student 2021' '2 Year Onsite Warranty']",
    image: "https://example.com/lenovo-image2.jpg",
  },
  {
    id: "laptop3",
    name: "ASUS VivoBook 15 (2022) Core i3 10th Gen - (8 GB/512 GB SSD/Windows 11 Home) X515JA-EJ362WS | X515JA-E",
    brand: "ASUS",
    price: 32990.0,
    ratings: 4.3,
    details:
      "['Intel Core i3 Processor (10th Gen)' '8 GB DDR4 RAM' '64 bit Windows 11 Operating System' '512 GB SSD' '39.62 cm (15.6 inch) Display' 'Office Home and Student 2021' '1 Year Onsite Warranty']",
    image: "https://example.com/asus-image.jpg",
  },
  {
    id: "laptop4",
    name: "realme Book (Slim) Core i3 11th Gen - (8 GB/256 GB SSD/Windows 10 Home) RMNB1001 Thin and Light Laptop",
    brand: "realme",
    price: 46990.0,
    ratings: 4.4,
    details:
      "['Stylish & Portable Thin and Light Laptop' '14 inch 2K QHD IPS LCD Display ( 400nits peak brightness 100% sRGB 3:2 aspect ratio Full Vision Display)' 'Finger Print Sensor for Faster System Access' 'Light Laptop without Optical Disk Drive' 'Intel Core i3 Processor (11th Gen)' '8 GB DDR4 RAM' '64 bit Windows 10 Operating System' '256 GB SSD' '35.56 cm (14 inch) Display' 'NA' '1 Year Domestic Warranty']",
    image: "https://example.com/realme-image.jpg",
  },
  {
    id: "laptop5",
    name: "DELL Inspiron Core i3 11th Gen - (8 GB/1 TB HDD/256 GB SSD/Windows 11 Home) D560841WIN9S Thin and Ligh...",
    brand: "DELL",
    price: 38990.0,
    ratings: 4.3,
    details:
      "'['Processor: Intel i3-1115G4 (Base- 1.70 GHz & Turbo up to 4.10 GHz) 2 Cores' 'RAM & Storage: 8GB DDR4 & 1TB + 256GB SSD' 'Graphics & Keyboard: Integrated & Standard Keyboard' 'Display: 15.6'' FHD WVA AG Narrow Border' 'Ports: 2x USB 3.2 Gen1 1x USB 2.0 HDMI 1.4 SD Card reader Audio jack 1 M.2 2230/2280 slot for solid-state drive/Intel Optane' 'Intel Core i3 Processor (11th Gen)' '8 GB DDR4 RAM' 'Windows 11 Operating System' '1 TB HDD|256 GB SSD' '39.62 cm (15.6 inch) Display' '1 YEAR']'",
    image: "https://example.com/dell-image.jpg",
  },
  {
    id: "laptop6",
    name: "HP 14s Intel Core i3 11th Gen - (8 GB/512 GB SSD/Windows 11 Home) 14s - dy2508TU Thin and Light Laptop",
    brand: "HP",
    price: 40990.0,
    ratings: 4.2,
    details:
      "['Intel Core i3 Processor (11th Gen)' '8 GB DDR4 RAM' '64 bit Windows 11 Operating System' '512 GB SSD' '35.56 cm (14 inch) Display' 'Microsoft Office Home & Student 2021' '1 Year Onsite Warranty']",
    image: "https://example.com/hp-image.jpg",
  },
  {
    id: "laptop7",
    name: "Lenovo IdeaPad 3 Ryzen 5 Hexa Core 5500U - (8 GB/512 GB SSD/Windows 11 Home) 15ALC6 Thin and Light Lap...",
    brand: "Lenovo",
    price: 44990.0,
    ratings: 4.3,
    details:
      "['AMD Ryzen 5 Hexa Core Processor' '8 GB DDR4 RAM' '64 bit Windows 11 Operating System' '512 GB SSD' '39.62 cm (15.6 inch) Display' 'Office Home and Student 2021' '2 Years Onsite Warranty']",
    image: "https://example.com/lenovo-image3.jpg",
  },
  {
    id: "laptop8",
    name: "Lenovo IdeaPad 1 Ryzen 5 Quad Core 3500U - (8 GB/512 GB SSD/Windows 11 Home) 15ADA7 Thin and Light Lap...",
    brand: "Lenovo",
    price: 38705.0,
    ratings: 4.2,
    details:
      "['AMD Ryzen 5 Quad Core Processor' '8 GB DDR4 RAM' '64 bit Windows 11 Operating System' '512 GB SSD' '39.62 cm (15.6 Inch) Display' '2 Years Onsite Warranty']",
    image: "https://example.com/lenovo-image4.jpg",
  },
  {
    id: "laptop9",
    name: "APPLE 2020 Macbook Air M1 - (8 GB/256 GB SSD/Mac OS Big Sur) MGN63HN/A",
    brand: "APPLE",
    price: 88990.0,
    ratings: 4.7,
    details:
      "['Apple M1 Processor' '8 GB DDR4 RAM' 'Mac OS Operating System' '256 GB SSD' '33.78 cm (13.3 inch) Display' 'Built-in Apps: iMovie Siri GarageBand Pages Numbers Photos Keynote Safari Mail FaceTime Messages Maps Stocks Home Voice Memos Notes Calendar Contacts Reminders Photo Booth Preview Books App Store Time Machine TV Music Podcasts Find My QuickTime Player' '1 Year Limited Warraadnty']",
    image: "https://example.com/apple-image.jpg",
  },
  {
    id: "laptop10",
    name: "ASUS VivoBook K15 OLED (2022) Core i3 11th Gen - (8 GB/256 GB SSD/Windows 11 Home) K513EA-L302WS Thin ...",
    brand: "ASUS",
    price: 40990.0,
    ratings: 4.4,
    details: [
      "Intel Core i3 Processor (11th Gen)",
      "8 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "256 GB SSD",
      "39.62 cm (15.6 inch) Display",
      "Office Home and Student 2021",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/asus-laptop10-image.jpg",
  },
  {
    id: "laptop11",
    name: "ASUS VivoBook 14 (2022) Ryzen 7 Quad Core AMD R7-3700U - (16 GB/512 GB SSD/Windows 11 Home) M415DA-EB5...",
    brand: "ASUS",
    price: 44990.0,
    ratings: 4.1,
    details: [
      "AMD Ryzen 7 Quad Core Processor",
      "16 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "512 GB SSD",
      "35.56 cm (14 inch) Display",
      "Office Home and Student 2021",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/asus-laptop11-image.jpg",
  },
  {
    id: "laptop12",
    name: "Lenovo Thinkpad Ryzen 5 Hexa Core 5600U - (8 GB/512 GB SSD/DOS) E14 AMD Gen3 Thin and Light Laptop",
    brand: "Lenovo",
    price: 69990.0,
    ratings: 4.5,
    details: [
      "AMD Ryzen 5 Hexa Core Processor",
      "8 GB DDR4 RAM",
      "64 bit DOS Operating System",
      "512 GB SSD",
      "35.56 cm (14 inch) Display",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/lenovo-laptop12-image.jpg",
  },
  {
    id: "laptop13",
    name: "Lenovo Core i3 11th Gen - (4 GB/256 GB SSD/Windows 10 Home) V15 ITL G2 Thin and Light Laptop",
    brand: "Lenovo",
    price: 38990.0,
    ratings: 4.3,
    details: [
      "Intel Core i3 Processor (11th Gen)",
      "4 GB DDR4 RAM",
      "64 bit Windows 10 Operating System",
      "256 GB SSD",
      "38.1 cm (15 inch) Display",
      "Microsoft Office Home & Student 2019",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/lenovo-laptop13-image.jpg",
  },
  {
    id: "laptop14",
    name: "HP Pavilion Ryzen 5 Hexa Core AMD R5-5600H - (8 GB/512 GB SSD/Windows 11 Home/4 GB Graphics/NVIDIA GeF...",
    brand: "HP",
    price: 59990.0,
    ratings: 4.5,
    details: [
      "AMD Ryzen 5 Hexa Core Processor",
      "8 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "512 GB SSD",
      "39.62 cm (15.6 inch) Display",
      "Microsoft Office Home & Student 2019",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/hp-laptop14-image.jpg",
  },
  {
    id: "laptop15",
    name: "HP 15s Intel Core i5 12th Gen - (8 GB/512 GB SSD/Windows 11 Home) 15s-fq5111TU Thin and Light Laptop",
    brand: "HP",
    price: 58990.0,
    ratings: 4.2,
    details: [
      "Intel Core i5 Processor (12th Gen)",
      "8 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "512 GB SSD",
      "39.62 cm (15.6 inch) Display",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/hp-laptop15-image.jpg",
  },
  {
    id: "laptop16",
    name: "Lenovo ThinkBook 13s Core i5 11th Gen - (8 GB/512 GB SSD/Windows 10 Home) TB13s ITL Gen 2 Thin and Lig...",
    brand: "Lenovo",
    price: 73990.0,
    ratings: 4.0,
    details: [
      "Intel Core i5 Processor (11th Gen)",
      "8 GB DDR4 RAM",
      "64 bit Windows 10 Operating System",
      "512 GB SSD",
      "33.02 cm (13 inch) Display",
      "Microsoft Office Home & Student 2019",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/lenovo-laptop16-image.jpg",
  },
  {
    id: "laptop17",
    name: "Lenovo IdeaPad Gaming Core i5 11th Gen - (8 GB/512 GB SSD/Windows 11 Home/4 GB Graphics/NVIDIA GeForce...",
    brand: "Lenovo",
    price: 51990.0,
    ratings: 4.3,
    details: [
      "Intel Core i5 Processor (11th Gen)",
      "8 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "512 GB SSD",
      "39.62 cm (15.6 Inch) Display",
      "1 Year Onsite Warranty + 1 Year Premium Care + 1 Year Accidentaly Damage Protection",
    ],
    image: "https://example.com/lenovo-laptop17-image.jpg",
  },
  {
    id: "laptop18",
    name: "acer Aspire 7 Core i5 12th Gen - (16 GB/512 GB SSD/Windows 11 Home/4 GB Graphics/NVIDIA GeForce GTX 16...",
    brand: "acer",
    price: 58990.0,
    ratings: 4.3,
    details: [
      "Intel Core i5 Processor (12th Gen)",
      "16 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "512 GB SSD",
      "39.62 cm (15.6 inch) Display",
      "Acer Care Center Acer Product Registration Nitro Sense Quick Access",
      "1 Year International Travelers Warranty (ITW)",
    ],
    image: "https://example.com/acer-laptop18-image.jpg",
  },
  {
    id: "laptop19",
    name: "ASUS TUF Gaming A15 with 90Whr Battery Ryzen 7 Octa Core 5800H - (16 GB/512 GB SSD/Windows 11 Home/6 G...",
    brand: "ASUS",
    price: 89990.0,
    ratings: 4.6,
    details: [
      "AMD Ryzen 7 Octa Core Processor",
      "16 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "512 GB SSD",
      "39.62 cm (15.6 Inch) Display",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/asus-laptop19-image.jpg",
  },
  {
    id: "laptop20",
    name: "HP Ryzen 3 Dual Core 3250U - (8 GB/256 GB SSD/Windows 11 Home) 15s-ey1508AU Thin and Light Laptop",
    brand: "HP",
    price: 27123.0,
    ratings: 4.1,
    details: [
      "AMD Ryzen 3 Dual Core Processor",
      "8 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "256 GB SSD",
      "39.62 cm (15.6 mm) Display",
      "Microsoft Office 2021 Home and Student HP Documentation HP BIOS recovery HP Smart",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/hp-laptop20-image.jpg",
  },
  {
    id: "laptop21",
    name: "ASUS VivoBook 15 (2022) Core i5 11th Gen - (8 GB/1 TB HDD/256 GB SSD/Windows 11 Home) X515EA-EJ502WS T...",
    brand: "ASUS",
    price: 47990.0,
    ratings: 4.3,
    details: [
      "Intel Core i5 Processor (11th Gen)",
      "8 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "1 TB HDD|256 GB SSD",
      "39.62 cm (15.6 inch) Display",
      "Office Home and Student 2021",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/asus-laptop21-image.jpg",
  },
  {
    id: "laptop22",
    name: "realme Book(Slim) Intel Evo Core i5 11th Gen - (8 GB/512 GB SSD/Windows 10 Home) RMNB1002 Thin and Lig...",
    brand: "realme",
    price: 59990.0,
    ratings: 4.4,
    details: [
      "Powered by 11th Gen Intel Evo Core i5 Processor",
      "Microsoft Office 2019 Home & Student Included",
      "Stylish Thin and Light Laptop without Optical Disk Drive",
      "Intel Core i5 Processor (11th Gen)",
      "8 GB DDR4 RAM",
      "64 bit Windows 10 Operating System",
      "512 GB SSD",
      "35.56 cm (14 inch) Display",
      "Microsoft Office 2019 Home & Student",
      "1 Year Domestic Warranty",
    ],
    image: "https://example.com/realme-laptop22-image.jpg",
  },
  {
    id: "laptop23",
    name: "MSI GF63 Thin Core i5 11th Gen - (8 GB/512 GB SSD/Windows 11 Home/4 GB Graphics/NVIDIA GeForce GTX 165...",
    brand: "MSI",
    price: 51990.0,
    ratings: 4.4,
    details: [
      "Intel Core i5 Processor (11th Gen)",
      "8 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "512 GB SSD",
      "39.62 cm (15.6 inch) Display",
      "Windows 11 Home MSI Center CoolerBoost",
      "2 Year On-Site & Carry-In Warranty",
    ],
    image: "https://example.com/msi-laptop23-image.jpg",
  },
  {
    id: "laptop24",
    name: "ASUS Vivobook 15 Core i3 10th Gen - (8 GB/512 GB SSD/Windows 11 Home) X515JA-EJ382WS X515JA Laptop",
    brand: "ASUS",
    price: 33849.0,
    ratings: 4.2,
    details: [
      "Intel Core i3 Processor (10th Gen)",
      "8 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "512 GB SSD",
      "39.62 cm (15.6 inch) Display",
      "Windows 11 Microsoft Office H&S 2021 1 Year McAfee",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/asus-laptop24-image.jpg",
  },
  {
    id: "laptop25",
    name: "Infinix INBook X2 Plus Core i7 11th Gen - (16 GB/512 GB SSD/Windows 11 Home) XL25 Thin and Light Lapto...",
    brand: "Infinix",
    price: 52990.0,
    ratings: 4.8,
    details: [
      "Intel Core i7 Processor (11th Gen)",
      "16 GB LPDDR4X RAM",
      "64 bit Windows 11 Operating System",
      "512 GB SSD",
      "39.62 cm (15.6 Inch) Display",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/infinix-laptop25-image.jpg",
  },
  {
    id: "laptop26",
    name: "HP Ryzen 5 Hexa Core 5500U - (8 GB/512 GB SSD/Windows 11 Home) 15s- eq2144au Thin and Light Laptop",
    brand: "HP",
    price: 50990.0,
    ratings: 4.3,
    details: [
      "AMD Ryzen 5 Hexa Core Processor",
      "8 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "512 GB SSD",
      "39.62 cm (15.6 inch) Display",
      "Microsoft Office Home 2019 & Office 365 HP Documentation HP SSRM HP Smart",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/hp-laptop26-image.jpg",
  },
  {
    id: "laptop27",
    name: "DELL Inspiron Athlon Dual Core 3050U - (8 GB/256 GB SSD/Windows 11 Home) Inspiron 3525 Notebook",
    brand: "DELL",
    price: 31990.0,
    ratings: 4.2,
    details: [
      "Processor: AMD Athlon Silver 3050U (2.30 GHz up to 3.20 GHz)",
      "RAM & Storage: 8GB DDR4 & 256GB SSD",
      "Display: 15.6'' HD AG Narrow Border",
      "Software: Win 11 + Office H&S 2021",
      "Ports: 2 USB 3.2 Gen 1 ports 1 USB 2.0 port 1 Headset jack 1 HDMI 1.4 port* 1 SD 3.0 card slot",
      "WiFi & BT: 802.11ac 1x1 WiFi and Bluetooth",
      "AMD Athlon Dual Core Processor",
      "8 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "256 GB SSD",
      "39.62 cm (15.6 Inch) Display",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/dell-laptop27-image.jpg",
  },
  {
    id: "laptop28",
    name: "ASUS TUF Gaming A17 with 90Whr Battery Ryzen 5 Hexa Core AMD R5-4600H - (8 GB/512 GB SSD/Windows 11 Ho...",
    brand: "ASUS",
    price: 52990.0,
    ratings: 4.4,
    details: [
      "AMD Ryzen 5 Hexa Core Processor",
      "8 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "512 GB SSD",
      "43.94 cm (17.3 Inch) Display",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/asus-laptop28-image.jpg",
  },
  {
    id: "laptop29",
    name: "RedmiBook Pro Core i3 11th Gen - (8 GB/256 GB SSD/Windows 11 Home) Thin and Light Laptop",
    brand: "RedmiBook",
    price: 31990.0,
    ratings: 4.2,
    details: [
      "Intel Core i3 Processor (11th Gen)",
      "8 GB DDR4 RAM",
      "Windows 11 Operating System",
      "256 GB SSD",
      "39.62 cm (15.6 inch) Display",
      "MS Office Home & Student 2019 Mi Smart Share DTS Audio processing",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/redmibook-laptop29-image.jpg",
  },
  {
    id: "laptop30",
    name: "ASUS Vivobook 14 (2022) Core i5 12th Gen - (8 GB/512 GB SSD/Windows 11 Home) X1402ZA-EK522WS Thin and ...",
    brand: "ASUS",
    price: 56990.0,
    ratings: 4.0,
    details: [
      "Intel Core i5 Processor (12th Gen)",
      "8 GB DDR4 RAM",
      "Windows 11 Operating System",
      "512 GB SSD",
      "35.56 cm (14 inch) Display",
      "Microsoft Office Home & Student 2021",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/asus-laptop30-image.jpg",
  },
  {
    id: "laptop31",
    name: "ASUS Vivobook Pro 15 Ryzen 7 Octa Core AMD R7-4800H - (16 GB/512 GB SSD/Windows 11 Home/4 GB Graphics/...",
    brand: "ASUS",
    price: 57990.0,
    ratings: 4.5,
    details: [
      "AMD Ryzen 7 Octa Core Processor",
      "16 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "512 GB SSD",
      "39.62 cm (15.6 Inch) Display",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/asus-laptop31-image.jpg",
  },
  {
    id: "laptop32",
    name: "APPLE 2022 MacBook AIR M2 - (8 GB/256 GB SSD/Mac OS Monterey) MLY33HN/A",
    brand: "APPLE",
    price: 112990.0,
    ratings: 4.8,
    details: [
      "Apple M2 Processor",
      "8 GB Unified Memory RAM",
      "Mac OS Operating System",
      "256 GB SSD",
      "34.54 cm (13.6 Inch) Display",
      "Built-in Apps: iMovie Siri GarageBand Pages Numbers Photos Keynote Safari Mail FaceTime Messages Maps Stocks Home Voice Memos Notes Calendar Contacts Reminders Photo Booth Preview Books App Store Time Machine TV Music Podcasts Find My QuickTime Player",
      "1 Year Limited Warranty",
    ],
    image: "https://example.com/apple-laptop32-image.jpg",
  },
  {
    id: "laptop34",
    name: "ASUS VivoBook Ultra 14 (2021) Core i5 11th Gen - (16 GB/512 GB SSD/Windows 11 Home) X413EA-EB533WS Thin...",
    brand: "ASUS",
    price: 53990.0,
    ratings: 4.4,
    details: [
      "Intel Core i5 Processor (11th Gen)",
      "16 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "512 GB SSD",
      "35.56 cm (14 inch) Display",
      "Office Home and Student 2021",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/asus-laptop34-image.jpg",
  },
  {
    id: "laptop35",
    name: "ASUS Vivobook 15 Touch Core i3 11th Gen - (8 GB/512 GB SSD/Windows 11 Home) X515EA-EZ311WS Thin and Li...",
    brand: "ASUS",
    price: 39990.0,
    ratings: 4.3,
    details: [
      "Intel Core i3 Processor (11th Gen)",
      "8 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "512 GB SSD",
      "39.62 cm (15.6 Inch) Touchscreen Display",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/asus-laptop35-image.jpg",
  },
  {
    id: "laptop36",
    name: "ASUS VivoBook K15 OLED (2022) Core i5 11th Gen - (16 GB/1 TB HDD/256 GB SSD/Windows 11 Home) K513EA-L5...",
    brand: "ASUS",
    price: 64990.0,
    ratings: 4.4,
    details: [
      "Intel Core i5 Processor (11th Gen)",
      "16 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "1 TB HDD|256 GB SSD",
      "39.62 cm (15.6 inch) Display",
      "Office Home and Student 2021",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/asus-laptop36-image.jpg",
  },
  {
    id: "laptop37",
    name: "APPLE 2022 MacBook Pro M2 - (8 GB/256 GB SSD/Mac OS Monterey) MNEP3HN/A",
    brand: "APPLE",
    price: 121990.0,
    ratings: 4.6,
    details: [
      "Apple M2 Processor",
      "8 GB Unified Memory RAM",
      "Mac OS Operating System",
      "256 GB SSD",
      "33.78 cm (13.3 Inch) Display",
      "Built-in Apps: iMovie Siri GarageBand Pages Numbers Photos Keynote Safari Mail FaceTime Messages Maps Stocks Home Voice Memos Notes Calendar Contacts Reminders Photo Booth Preview Books App Store Time Machine TV Music Podcasts Find My QuickTime Player",
      "1 Year Limited Warranty",
    ],
    image: "https://example.com/apple-laptop37-image.jpg",
  },
  {
    id: "laptop38",
    name: "Infinix X1 Slim Series Core i3 10th Gen - (8 GB/256 GB SSD/Windows 11 Home) XL21 Thin and Light Laptop",
    brand: "Infinix",
    price: 28990.0,
    ratings: 4.2,
    details: [
      "Intel Core i3 Processor (10th Gen)",
      "8 GB LPDDR4X RAM",
      "64 bit Windows 11 Operating System",
      "256 GB SSD",
      "35.56 cm (14 inch) Display",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/infinix-laptop38-image.jpg",
  },
  {
    id: "laptop39",
    name: "ASUS Vivobook 14 (2022) Core i5 12th Gen - (16 GB/512 GB SSD/Windows 11 Home) X1402ZA-MW512WS Thin and...",
    brand: "ASUS",
    price: 66990.0,
    ratings: 4.9,
    details: [
      "Intel Core i5 Processor (12th Gen)",
      "16 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "512 GB SSD",
      "35.56 cm (14 Inch) Touchscreen Display",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/asus-laptop39-image.jpg",
  },
  {
    id: "laptop40",
    name: "Infinix X1 Slim Series Core i5 10th Gen - (16 GB/512 GB SSD/Windows 11 Home) XL21 Thin and Light Lapto...",
    brand: "Infinix",
    price: 37990.0,
    ratings: 4.1,
    details: [
      "Intel Core i5 Processor (10th Gen)",
      "16 GB LPDDR4X RAM",
      "64 bit Windows 11 Operating System",
      "512 GB SSD",
      "35.56 cm (14 Inch) Display",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/infinix-laptop40-image.jpg",
  },
  {
    id: "laptop41",
    name: "HP Athlon Dual Core 3050U - (8 GB/256 GB SSD/Windows 11 Home) 14s-fq0568AU Thin and Light Laptop",
    brand: "HP",
    price: 25990.0,
    ratings: 3.9,
    details: [
      "AMD Athlon Dual Core Processor",
      "8 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "256 GB SSD",
      "35.56 cm (14 inch) Display",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/hp-laptop41-image.jpg",
  },
  {
    id: "laptop42",
    name: "MSI Katana GF66 Core i7 11th Gen - (16 GB/512 GB SSD/Windows 10 Home/6 GB Graphics/NVIDIA GeForce RTX ...",
    brand: "MSI",
    price: 84990.0,
    ratings: 4.3,
    details: [
      "Intel Core i7 Processor (11th Gen)",
      "16 GB DDR4 RAM",
      "64 bit Windows 10 Operating System",
      "512 GB SSD",
      "39.62 cm (15.6 inch) Display",
      "2 Year Carry-In Warranty Term",
    ],
    image: "https://example.com/msi-laptop42-image.jpg",
  },
  {
    id: "laptop43",
    name: "Lenovo Thinkpad Ryzen 5 Hexa Core 5600U - (8 GB/512 GB SSD/DOS) E14 AMD Gen3 Thin and Light Laptop",
    brand: "Lenovo",
    price: 65499.0,
    ratings: 4.5,
    details: [
      "AMD Ryzen 5 Hexa Core Processor",
      "8 GB DDR4 RAM",
      "64 bit DOS Operating System",
      "512 GB SSD",
      "35.56 cm (14 inch) Display",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/lenovo-laptop43-image.jpg",
  },
  {
    id: "laptop44",
    name: "Lenovo IdeaPad 3 Core i3 10th Gen - (8 GB/256 GB SSD/Windows 11 Home) 81WA00Q3IN|81WA00MEIN Thin and L...",
    brand: "Lenovo",
    price: 33990.0,
    ratings: 4.3,
    details: [
      "Intel Core i3 Processor (10th Gen)",
      "8 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "256 GB SSD",
      "35.56 cm (14 inch) Display",
      "2 Years Onsite Warranty",
    ],
    image: "https://example.com/lenovo-laptop44-image.jpg",
  },
  {
    id: "laptop45",
    name: "APPLE 2021 Macbook Pro M1 Max - (32 GB/1 TB SSD/Mac OS Monterey) MK1A3HN/A",
    brand: "APPLE",
    price: 309490.0,
    ratings: 4.3,
    details: [
      "Apple M1 Max Processor",
      "32 GB Unified Memory RAM",
      "Mac OS Operating System",
      "1 TB SSD",
      "41.15 cm (16.2 inch) Display",
      "iMovie Siri GarageBand Pages Numbers Photos Keynote Safari Mail FaceTime Messages Maps Stocks Home Voice Memos Notes Calendar Contacts Reminders Photo Booth Preview Books App Store Time Machine TV Music Podcasts Find My QuickTime Player",
      "1 Year Limited Warranty",
    ],
    image: "https://example.com/apple-laptop45-image.jpg",
  },
  {
    id: "laptop46",
    name: "HP Ryzen 3 Quad Core 5300U - (8 GB/512 GB SSD/Windows 11 Home) 15s-eq2143au Thin and Light Laptop",
    brand: "HP",
    price: 37499.0,
    ratings: 4.2,
    details: [
      "AMD Ryzen 3 Quad Core Processor",
      "8 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "512 GB SSD",
      "39.62 cm (15.6 inch) Display",
      "Microsoft Office 2019 & Office 365 HP Documentation HP BIOS recovery HP Smart",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/hp-laptop46-image.jpg",
  },
  {
    id: "laptop47",
    name: "ASUS VivoBook Ultra 14 (2022) Core i3 11th Gen - (8 GB/512 GB SSD/Windows 11 Home) X413EA-EB322WS Thin...",
    brand: "ASUS",
    price: 38990.0,
    ratings: 4.4,
    details: [
      "Intel Core i3 Processor (11th Gen)",
      "8 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "512 GB SSD",
      "35.56 cm (14 inch) Display",
      "Office Home and Student 2021",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/asus-laptop47-image.jpg",
  },
  {
    id: "laptop48",
    name: "Lenovo IdeaPad 3 Celeron Dual Core - (8 GB/256 GB SSD/Windows 11 Home) 81WQ00MQIN|81WQ00NXIN Laptop",
    brand: "Lenovo",
    price: 28990.0,
    ratings: 4.1,
    details: [
      "Intel Celeron Dual Core Processor",
      "8 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "256 GB SSD",
      "39.62 cm (15.6 Inch) Display",
      "2 Years Onsite Warranty",
    ],
    image: "https://example.com/lenovo-laptop48-image.jpg",
  },
  {
    id: "laptop49",
    name: "ASUS VivoBook 14 (2021) Celeron Dual Core - (4 GB/256 GB SSD/Windows 11 Home) X415MA-BV011W Thin and L...",
    brand: "ASUS",
    price: 23990.0,
    ratings: 4.0,
    details: [
      "Intel Celeron Dual Core Processor",
      "4 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "256 GB SSD",
      "35.56 cm (14 inch) Display",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/asus-laptop49-image.jpg",
  },
  {
    id: "laptop50",
    name: "APPLE 2022 MacBook AIR M2 - (8 GB/512 GB SSD/Mac OS Monterey) MLY23HN/A",
    brand: "APPLE",
    price: 139990.0,
    ratings: 4.7,
    details: [
      "Apple M2 Processor",
      "8 GB Unified Memory RAM",
      "Mac OS Operating System",
      "512 GB SSD",
      "34.54 cm (13.6 Inch) Display",
      "Built-in Apps: iMovie Siri GarageBand Pages Numbers Photos Keynote Safari Mail FaceTime Messages Maps Stocks Home Voice Memos Notes Calendar Contacts Reminders Photo Booth Preview Books App Store Time Machine TV Music Podcasts Find My QuickTime Player",
      "1 Year Limited Warranty",
    ],
    image: "https://example.com/apple-laptop50-image.jpg",
  },
  {
    id: "laptop51",
    name: "ASUS TUF Gaming F15 Core i5 10th Gen - (8 GB/1 TB SSD/Windows 11 Home/4 GB Graphics/NVIDIA GeForce GTX...",
    brand: "ASUS",
    price: 59990.0,
    ratings: 4.5,
    details: [
      "Intel Core i5 Processor (10th Gen)",
      "8 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "1 TB SSD",
      "39.62 cm (15.6 Inch) Display",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/asus-laptop51-image.jpg",
  },
  {
    id: "laptop52",
    name: "Infinix INBook X1 Neo Series Celeron Quad Core - (4 GB/128 GB SSD/Windows 11 Home) XL22 Thin and Light...",
    brand: "Infinix",
    price: 20990.0,
    ratings: 4.2,
    details: [
      "Intel Celeron Quad Core Processor",
      "4 GB LPDDR4X RAM",
      "64 bit Windows 11 Operating System",
      "128 GB SSD",
      "35.56 cm (14 inch) Display",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/infinix-laptop52-image.jpg",
  },
  {
    id: "laptop53",
    name: "HP 15s Intel Core i3 11th Gen - (8 GB/512 GB SSD/Windows 11 Home) 15s-fq2671TU Thin and Light Laptop",
    brand: "HP",
    price: 39490.0,
    ratings: 4.2,
    details: [
      "Intel Core i3 Processor (11th Gen)",
      "8 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "512 GB SSD",
      "39.62 cm (15.6 inch) Display",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/hp-laptop53-image.jpg",
  },
  {
    id: "laptop54",
    name: "HP Ryzen 5 Hexa Core 5500U - (8 GB/512 GB SSD/Windows 11 Home) 14s-fq1092au Thin and Light Laptop",
    brand: "HP",
    price: 49990.0,
    ratings: 4.2,
    details: [
      "AMD Ryzen 5 Hexa Core Processor",
      "8 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "512 GB SSD",
      "35.56 cm (14 inch) Display",
      "Microsoft Office Home & Student 2019 HP Documentation HP SSRM HP Smart",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/hp-laptop54-image.jpg",
  },
  {
    id: "laptop55",
    name: "HP Victus Intel Core i5 12th Gen - (8 GB/512 GB SSD/Windows 11 Home/4 GB Graphics/NVIDIA GeForce GTX 1...",
    brand: "HP",
    price: 65990.0,
    ratings: 4.3,
    details: [
      "Intel Core i5 Processor (12th Gen)",
      "8 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "512 GB SSD",
      "39.62 cm (15.6 Inch) Display",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/hp-laptop55-image.jpg",
  },
  {
    id: "laptop56",
    name: "ASUS VivoBook K15 OLED (2022) Core i3 11th Gen - (8 GB/512 GB SSD/Windows 11 Home) K513EA-L312WS Thin ...",
    brand: "ASUS",
    price: 45990.0,
    ratings: 4.5,
    details: [
      "Intel Core i3 Processor (11th Gen)",
      "8 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "512 GB SSD",
      "39.62 cm (15.6 inch) Display",
      "Office Home and Student 2021",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/asus-laptop56-image.jpg",
  },
  {
    id: "laptop57",
    name: "ASUS TUF Gaming F15 (2022) Core i7 12th Gen - (16 GB/512 GB SSD/Windows 11 Home/4 GB Graphics/NVIDIA G...",
    brand: "ASUS",
    price: 100990.0,
    ratings: 4.5,
    details: [
      "Intel Core i7 Processor (12th Gen)",
      "16 GB DDR5 RAM",
      "64 bit Windows 11 Operating System",
      "512 GB SSD",
      "39.62 cm (15.6 inch) Display",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/asus-laptop57-image.jpg",
  },
  {
    id: "laptop58",
    name: "Lenovo IdeaPad 3 Core i5 12th Gen - (8 GB/512 GB SSD/Windows 11 Home) 15IAU7 Thin and Light Laptop",
    brand: "Lenovo",
    price: 53490.0,
    ratings: 4.2,
    details: [
      "Intel Core i5 Processor (12th Gen)",
      "8 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "512 GB SSD",
      "39.62 cm (15.6 Inch) Display",
      "2 Year Onsite Warranty",
    ],
    image: "https://example.com/lenovo-laptop58-image.jpg",
  },
  {
    id: "laptop59",
    name: "acer Extensa Core i3 11th Gen - (8 GB/256 GB SSD/Windows 11 Home) EX 215-54 Thin and Light Laptop",
    brand: "acer",
    price: 29990.0,
    ratings: 4.3,
    details: [
      "Intel Core i3 Processor (11th Gen)",
      "8 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "256 GB SSD",
      "39.62 cm (15.6 Inch) Display",
      "1 Year International Travelers Warranty (ITW)",
    ],
    image: "https://example.com/acer-laptop59-image.jpg",
  },
  {
    id: "laptop60",
    name: "ASUS VivoBook 15 (2022) Core i3 11th Gen - (8 GB/1 TB HDD/256 GB SSD/Windows 11 Home) X515EA-EJ332WS T...",
    brand: "ASUS",
    price: 38990.0,
    ratings: 4.3,
    details: [
      "Intel Core i3 Processor (11th Gen)",
      "8 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "1 TB HDD|256 GB SSD",
      "39.62 cm (15.6 inch) Display",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/asus-laptop60-image.jpg",
  },
  {
    id: "laptop61",
    name: "ASUS Vivobook Pro 14X OLED with ASUS DialPad Ryzen 9 Octa Core 5900HX - (8 GB/1 TB SSD/Windows 10 Home...",
    brand: "ASUS",
    price: 94990.0,
    ratings: 4.1,
    details: [
      "AMD Ryzen 9 Octa Core Processor",
      "8 GB DDR4 RAM",
      "64 bit Windows 10 Operating System",
      "1 TB SSD",
      "35.56 cm (14 Inch) Display",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/image1.jpg",
  },
  {
    id: "laptop62",
    name: "acer Nitro 5 Ryzen 5 Hexa Core AMD R5-5600H - (8 GB/512 GB SSD/Windows 11 Home/4 GB Graphics/NVIDIA Ge...",
    brand: "acer",
    price: 54990.0,
    ratings: 4.5,
    details: [
      "AMD Ryzen 5 Hexa Core Processor",
      "8 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "512 GB SSD",
      "39.62 cm (15.6 Inch) Display",
      "Acer Care Center Acer Product Registration NitroSense Quick Access",
      "1 Year International Travelers Warranty (ITW)",
    ],
    image: "https://example.com/image2.jpg",
  },
  {
    id: "laptop63",
    name: "ASUS VivoBook 15 Core i3 10th Gen - (8 GB/1 TB HDD/Windows 10 Home) X515JA-EJ322TS Thin and Light Lapt...",
    brand: "ASUS",
    price: 37990.0,
    ratings: 4.0,
    details: [
      "Intel Core i3 Processor (10th Gen)",
      "8 GB DDR4 RAM",
      "64 bit Windows 10 Operating System",
      "1 TB HDD",
      "39.62 cm (15.6 inch) Display",
      "Microsoft Office Home and Student 2019 Splendid Tru2Life My Asus",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/image3.jpg",
  },
  {
    id: "laptop64",
    name: "APPLE MacBook Air M1 - (16 GB/256 GB SSD/Mac OS Big Sur) Z124J005KD",
    brand: "APPLE",
    price: 104990.0,
    ratings: 4.7,
    details: [
      "Apple M1 Processor",
      "16 GB DDR4 RAM",
      "Mac OS Operating System",
      "256 GB SSD",
      "33.78 cm (13.3 inch) Display",
      "Built-in Apps: iMovie Siri GarageBand Pages Numbers Photos Keynote Safari Mail FaceTime Messages Maps Stocks Home Voice Memos Notes Calendar Contacts Reminders Photo Booth Preview Books App Store Time Machine TV Music Podcasts Find My QuickTime Player",
      "1 Year Limited Warranty",
    ],
    image: "https://example.com/image4.jpg",
  },
  {
    id: "laptop65",
    name: "DELL Inspiron Ryzen 5 Quad Core 3450U - (8 GB/256 GB SSD/Windows 10) Inspiron 3505 Notebook",
    brand: "DELL",
    price: 41590.0,
    ratings: 4.3,
    details: [
      "AMD Ryzen 5 Quad Core Processor",
      "8 GB DDR4 RAM",
      "64 bit Windows 10 Operating System",
      "256 GB SSD",
      "39.62 cm (15.6 Inch) Display",
      "Microsoft Office Home & Student 2019",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/image5.jpg",
  },
  {
    id: "laptop66",
    name: "DELL Inspiron Core i3 11th Gen - (8 GB/512 GB SSD/Windows 11 Home) Inspiron 3511 Thin and Light Laptop",
    brand: "DELL",
    price: 43999.0,
    ratings: 3.3,
    details: [
      "Intel Core i3 Processor (11th Gen)",
      "8 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "512 GB SSD",
      "39.62 cm (15.6 inch) Display",
      "Microsoft Office Home & Student 2021",
      "1 Year Onsite Hardware Service",
    ],
    image: "https://example.com/image6.jpg",
  },
  {
    id: "laptop67",
    name: "HP OMEN Ryzen 5 Hexa Core 4600H - (8 GB/512 GB SSD/Windows 10 Home/4 GB Graphics/NVIDIA GeForce GTX 165...",
    brand: "HP",
    price: 71990.0,
    ratings: 4.3,
    details: [
      "AMD Ryzen 5 Hexa Core Processor",
      "8 GB DDR4 RAM",
      "64 bit Windows 10 Operating System",
      "512 GB SSD",
      "39.62 cm (15.6 inch) Display",
      "HP Audio Switch HP Support Assistant HP Connection Optimizer",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/image7.jpg",
  },
  {
    id: "laptop68",
    name: "ASUS VivoBook Ultra K14 (2021) Core i3 11th Gen - (8 GB/512 GB SSD/Windows 10 Home) X413EA-EB372TS Thi...",
    brand: "ASUS",
    price: 43990.0,
    ratings: 4.2,
    details: [
      "Intel Core i3 Processor (11th Gen)",
      "8 GB DDR4 RAM",
      "64 bit Windows 10 Operating System",
      "512 GB SSD",
      "35.56 cm (14 inch) Display",
      "Tru2Life",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/image8.jpg",
  },
  {
    id: "laptop69",
    name: "ASUS VivoBook 15 Core i5 10th Gen - (8 GB/1 TB HDD/Windows 10 Home/2 GB Graphics) X512FA-EJ549T Laptop",
    brand: "ASUS",
    price: 47490.0,
    ratings: 4.3,
    details: [
      "Intel Core i5 Processor (10th Gen)",
      "8 GB DDR4 RAM",
      "64 bit Windows 10 Operating System",
      "1 TB HDD",
      "39.62 cm (15.6 inch) Display",
      "Splendid Tru2Life",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/image9.jpg",
  },
  {
    id: "laptop70",
    name: "ASUS Zenbook Flip 14 OLED (2022) Touch Panel Core i5 12th Gen - (16 GB/512 GB SSD/Windows 11 Home) UP5...",
    brand: "ASUS",
    price: 108990.0,
    ratings: 4.7,
    details: [
      "Intel Core i5 Processor (12th Gen)",
      "16 GB LPDDR5 RAM",
      "64 bit Windows 11 Operating System",
      "512 GB SSD",
      "35.56 cm (14 inch) Touchscreen Display",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/image1.jpg",
  },
  {
    id: "laptop71",
    name: "MSI Prestige 14 Core i7 10th Gen - (16 GB/512 GB SSD/Windows 10 Home/2 GB Graphics) Prestige 14 A10RAS...",
    brand: "MSI",
    price: 74990.0,
    ratings: 3.9,
    details: [
      "Intel Core i7 Processor (10th Gen)",
      "16 GB DDR4 RAM",
      "64 bit Windows 10 Operating System",
      "512 GB SSD",
      "35.56 cm (14 inch) Display",
      "Cooler Boost True Color 2.0 Nahimic 3 Creator Center",
      "1 Year Carry In Warranty",
    ],
    image: "https://example.com/image2.jpg",
  },
  {
    id: "laptop72",
    name: "ASUS Zenbook S 13 OLED Ryzen 5 Hexa Core 6600U - (16 GB/512 GB SSD/Windows 11 Home) UM5302TA-LX501WS T...",
    brand: "ASUS",
    price: 99990.0,
    ratings: 4.8,
    details: [
      "AMD Ryzen 5 Hexa Core Processor",
      "16 GB LPDDR5 RAM",
      "Windows 11 Operating System",
      "512 GB SSD",
      "33.78 cm (13.3 Inch) Touchscreen Display",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/image3.jpg",
  },
  {
    id: "laptop73",
    name: "APPLE 2022 MacBook AIR M2 - (8 GB/512 GB SSD/Mac OS Monterey) MLY43HN/A",
    brand: "APPLE",
    price: 139990.0,
    ratings: 4.6,
    details: [
      "Apple M2 Processor",
      "8 GB Unified Memory RAM",
      "Mac OS Operating System",
      "512 GB SSD",
      "34.54 cm (13.6 Inch) Display",
      "Built-in Apps: iMovie Siri GarageBand Pages Numbers Photos Keynote Safari Mail FaceTime Messages Maps Stocks Home Voice Memos Notes Calendar Contacts Reminders Photo Booth Preview Books App Store Time Machine TV Music Podcasts Find My QuickTime Player",
      "1 Year Limited Warranty",
    ],
    image: "https://example.com/image4.jpg",
  },
  {
    id: "laptop74",
    name: "DELL Vostro Core i3 10th Gen - (8 GB/512 GB SSD/Windows 11 Home) Vostro 3510 Thin and Light Laptop",
    brand: "DELL",
    price: 38990.0,
    ratings: 4.0,
    details: [
      "Intel Core i3 Processor (10th Gen)",
      "8 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "512 GB SSD",
      "39.62 cm (15.6 Inch) Display",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/image5.jpg",
  },
  {
    id: "laptop75",
    name: "DELL Inspiron Ryzen 7 Octa Core 5825U - (8 GB/512 GB SSD/Windows 11 Home) Inspiron 3525 Notebook",
    brand: "DELL",
    price: 59990.0,
    ratings: 4.1,
    details: [
      "Processor: AMD Ryzen 7-5825U (2.00 GHz up to 4.50 GHz)",
      "RAM & Storage: 8GB DDR4 (2 DIMM Slots) & 512GB SSD",
      "Software: Win 11 + Office H&S 2021",
      "Display: 15.6'' FHD WVA AG Narrow Border 120Hz 250 nits",
      "Ports: 1 USB 3.2 Gen 1 port 1 USB 3.2 Gen 1 Type-C port 1 USB 2.0 port 1 Headset jack 1 HDMI 1.4 port* 1 SD 3.0 card slot",
      "AMD Ryzen 7 Octa Core Processor",
      "8 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "512 GB SSD",
      "39.62 cm (15.6 inch) Display",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/image6.jpg",
  },
  {
    id: "laptop76",
    name: "APPLE 2022 MacBook AIR M2 - (8 GB/512 GB SSD/Mac OS Monterey) MLXX3HN/A",
    brand: "APPLE",
    price: 139990.0,
    ratings: 4.7,
    details: [
      "Apple M2 Processor",
      "8 GB Unified Memory RAM",
      "Mac OS Operating System",
      "512 GB SSD",
      "34.54 cm (13.6 Inch) Display",
      "Built-in Apps: iMovie Siri GarageBand Pages Numbers Photos Keynote Safari Mail FaceTime Messages Maps Stocks Home Voice Memos Notes Calendar Contacts Reminders Photo Booth Preview Books App Store Time Machine TV Music Podcasts Find My QuickTime Player",
      "1 Year Limited Warraadnty",
    ],
    image: "https://example.com/image7.jpg",
  },
  {
    id: "laptop77",
    name: "ASUS TUF Dash F15 (2022) Core i5 12th Gen - (8 GB/512 GB SSD/Windows 11 Home/4 GB Graphics/NVIDIA GeFo...",
    brand: "ASUS",
    price: 82990.0,
    ratings: 4.3,
    details: [
      "Intel Core i5 Processor (12th Gen)",
      "8 GB DDR5 RAM",
      "Windows 11 Operating System",
      "512 GB SSD",
      "39.62 cm (15.6 inch) Display",
      "Microsoft Office Home & Student",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/image8.jpg",
  },
  {
    id: "laptop78",
    name: "MSI Core i5 11th Gen - (8 GB/512 GB SSD/Windows 10 Home/4 GB Graphics/NVIDIA GeForce GTX 1650 MAX Q/14...",
    brand: "MSI",
    price: 49990.0,
    ratings: 4.5,
    details: [
      "Intel Core i5 Processor (11th Gen)",
      "8 GB DDR4 RAM",
      "64 bit Windows 10 Operating System",
      "512 GB SSD",
      "39.62 cm (15.6 Inch) Display",
      "2 Year Carry-In Warranty Term",
    ],
    image: "https://example.com/image9.jpg",
  },
  {
    id: "laptop79",
    name: "Infinix INBook X1 Core i3 10th Gen - (8 GB/256 GB SSD/Windows 11 Home) XL11 Thin and Light Laptop",
    brand: "Infinix",
    price: 29990.0,
    ratings: 4.3,
    details: [
      "Intel Core i3 Processor (10th Gen)",
      "8 GB LPDDR4X RAM",
      "64 bit Windows 11 Operating System",
      "256 GB SSD",
      "35.56 cm (14 inch) Display",
      "1 year Onsite Warranty",
    ],
    image: "https://example.com/image10.jpg",
  },
  {
    id: "laptop80",
    name: "ASUS ROG Strix G15 (2021) Ryzen 7 Octa Core AMD R7-4800H - (8 GB/512 GB SSD/Windows 10 Home/4 GB Graph...",
    brand: "ASUS",
    price: 76490.0,
    ratings: 4.5,
    details: [
      "AMD Ryzen 7 Octa Core Processor",
      "8 GB DDR4 RAM",
      "64 bit Windows 10 Operating System",
      "512 GB SSD",
      "39.62 cm (15.6 inch) Display",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/image11.jpg",
  },
  {
    id: "laptop81",
    name: "DELL Ryzen 7 Octa Core AMD R7-5800H - (16 GB/512 GB SSD/Windows 11 Home/4 GB Graphics/NVIDIA GeForce R...",
    brand: "DELL",
    price: 89081.0,
    ratings: 5.0,
    details: [
      "NVIDIA RTX 3050 Graphics upto 90W TGP",
      "15.6 inch Full HD AG Display (250 nits Brightness 120Hz Narrow Border)",
      "Alienware Command Center",
      "AMD Ryzen 7 Octa Core Processor",
      "16 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "512 GB SSD",
      "39.62 cm (15.6 inch) Display",
      "Office Home and Student 2021",
      "1 Year Premium Support",
    ],
    image: "https://example.com/image12.jpg",
  },
  {
    id: "laptop82",
    name: "ASUS Vivobook 14 Core i3 10th Gen - (4 GB/1 TB HDD/Windows 10 Home) X409FA-EK617T Thin and Light Lapto...",
    brand: "ASUS",
    price: 30650.0,
    ratings: 3.6,
    details: [
      "Intel Core i3 Processor (10th Gen)",
      "4 GB DDR4 RAM",
      "64 bit Windows 10 Operating System",
      "1 TB HDD",
      "35.81 cm (14.1 inch) Display",
      "1 Year Manufacturing Warranty",
    ],
    image: "https://example.com/image13.jpg",
  },
  {
    id: "laptop83",
    name: "ASUS ROG Strix G15 (2022) with 90Whr Battery Ryzen 7 Octa Core AMD R7-6800H - (16 GB/1 TB SSD/Windows ...",
    brand: "ASUS",
    price: 140990.0,
    ratings: 5.0,
    details: [
      "AMD Ryzen 7 Octa Core Processor",
      "16 GB DDR5 RAM",
      "Windows 11 Operating System",
      "1 TB SSD",
      "39.62 cm (15.6 inch) Display",
      "Microsoft Office Home & Student",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/image14.jpg",
  },
  {
    id: "laptop84",
    name: "Lenovo Ideapad Slim 3i (2021) Core i5 11th Gen - (8 GB/512 GB SSD/Windows 10 Home) 14 ITL 6 Thin and L...",
    brand: "Lenovo",
    price: 58000.0,
    ratings: 4.3,
    details: [
      "Intel Core i5 Processor (11th Gen)",
      "8 GB DDR4 RAM",
      "64 bit Windows 10 Operating System",
      "512 GB SSD",
      "35.56 cm (14 Inch) Display",
      "Microsoft Office Home and Student 2019",
      "2 Years Warranty",
    ],
    image: "https://example.com/image15.jpg",
  },
  {
    id: "laptop85",
    name: "ASUS VivoBook 14 (2022) Core i3 12th Gen - (8 GB/512 GB SSD/Windows 11 Home) X1402ZA-EB312WS Thin and ...",
    brand: "ASUS",
    price: 47990.0,
    ratings: 4.4,
    details: [
      "Intel Core i3 Processor (12th Gen)",
      "8 GB DDR4 RAM",
      "Windows 11 Operating System",
      "512 GB SSD",
      "35.56 cm (14 inch) Display",
      "Office Home and Student 2021",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/image16.jpg",
  },
  {
    id: "laptop86",
    name: "APPLE 2021 Macbook Pro M1 Pro - (16 GB/1 TB SSD/Mac OS Monterey) MKGQ3HN/A",
    brand: "APPLE",
    price: 222990.0,
    ratings: 4.8,
    details: [
      "Apple M1 Pro Processor",
      "16 GB Unified Memory RAM",
      "Mac OS Operating System",
      "1 TB SSD",
      "36.07 cm (14.2 inch) Display",
      "iMovie Siri GarageBand Pages Numbers Photos Keynote Safari Mail FaceTime Messages Maps Stocks Home Voice Memos Notes Calendar Contacts Reminders Photo Booth Preview Books App Store Time Machine TV Music Podcasts Find My QuickTime Player",
      "1 Year Limited Warranty",
    ],
    image: "https://example.com/image17.jpg",
  },
  {
    id: "laptop87",
    name: "HP Ryzen 3 Dual Core 3250U - (8 GB/512 GB SSD/Windows 11 Home) 15s- eq1560AU Thin and Light Laptop",
    brand: "HP",
    price: 33990.0,
    ratings: 4.3,
    details: [
      "AMD Ryzen 3 Dual Core Processor",
      "8 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "512 GB SSD",
      "39.62 cm (15.6 inch) Display",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/image18.jpg",
  },
  {
    id: "laptop88",
    name: "Infinix X1 Slim Series Core i5 10th Gen - (8 GB/512 GB SSD/Windows 11 Home) XL21 Thin and Light Laptop",
    brand: "Infinix",
    price: 36990.0,
    ratings: 4.2,
    details: [
      "Intel Core i5 Processor (10th Gen)",
      "8 GB LPDDR4X RAM",
      "64 bit Windows 11 Operating System",
      "512 GB SSD",
      "35.56 cm (14 Inch) Display",
      "NA",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/image19.jpg",
  },
  {
    id: "laptop89",
    name: "ASUS VivoBook K15 OLED (2022) Core i5 11th Gen - (16 GB/1 TB HDD/256 GB SSD/Windows 10 Home) K513EA-L5...",
    brand: "ASUS",
    price: 63990.0,
    ratings: 4.4,
    details: [
      "Intel Core i5 Processor (11th Gen)",
      "16 GB DDR4 RAM",
      "64 bit Windows 10 Operating System",
      "1 TB HDD|256 GB SSD",
      "39.62 cm (15.6 inch) Display",
      "Microsoft Office Home and Student 2019 AppDeals Splendid Tru2Life Link to MyASUS",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/image20.jpg",
  },
  {
    id: "laptop90",
    name: "Infinix INBook X2 Plus Core i3 11th Gen - (8 GB/256 GB SSD/Windows 11 Home) XL25 Thin and Light Laptop",
    brand: "Infinix",
    price: 32990.0,
    ratings: 4.4,
    details:
      "['Intel Core i3 Processor (11th Gen)' '8 GB LPDDR4X RAM' '64 bit Windows 11 Operating System' '256 GB SSD' '39.62 cm (15.6 Inch) Display' '1 Year Onsite Warranty']",
    image: "https://example.com/image20.jpg",
  },
  {
    id: "laptop91",
    name: "Infinix INBook X2 Plus Core i3 11th Gen - (8 GB/256 GB SSD/Windows 11 Home) XL25 Thin and Light Laptop",
    brand: "Infinix",
    price: 32990.0,
    ratings: 4.4,
    details: [
      "Intel Core i3 Processor (11th Gen)",
      "8 GB LPDDR4X RAM",
      "64 bit Windows 11 Operating System",
      "256 GB SSD",
      "39.62 cm (15.6 Inch) Display",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/image21.jpg",
  },
  {
    id: "laptop92",
    name: "ASUS TUF Gaming F15 Core i5 10th Gen - (8 GB/512 GB SSD/Windows 10 Home/4 GB Graphics/NVIDIA GeForce G...",
    brand: "ASUS",
    price: 64990.0,
    ratings: 4.5,
    details: [
      "Intel Core i5 Processor (10th Gen)",
      "8 GB DDR4 RAM",
      "64 bit Windows 10 Operating System",
      "512 GB SSD",
      "39.62 cm (15.6 Inch) Display",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/image22.jpg",
  },
  {
    id: "laptop93",
    name: "HP Pavilion Gaming Ryzen 7 Octa Core AMD R7-5800H - (16 GB/512 GB SSD/Windows 11 Home/4 GB Graphics/NV...",
    brand: "HP",
    price: 75990.0,
    ratings: 4.3,
    details: [
      "AMD Ryzen 7 Octa Core Processor",
      "16 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "512 GB SSD",
      "39.62 cm (15.6 inch) Display",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/image23.jpg",
  },
  {
    id: "laptop94",
    name: "HP Pavilion Ryzen 5 Hexa Core AMD R5-5600H - (8 GB/512 GB SSD/Windows 10 Home/4 GB Graphics/NVIDIA GeF...",
    brand: "HP",
    price: 60990.0,
    ratings: 4.4,
    details: [
      "AMD Ryzen 5 Hexa Core Processor",
      "8 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "512 GB SSD",
      "39.62 cm (15.6 Inch) Display",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/image24.jpg",
  },
  {
    id: "laptop95",
    name: "DELL Vostro Core i5 11th Gen - (8 GB/512 GB SSD/Windows 10/2 GB Graphics) Vostro 3400 Thin and Light L...",
    brand: "DELL",
    price: 63090.0,
    ratings: 3.9,
    details: [
      "Intel Core i5 Processor (11th Gen)",
      "8 GB DDR4 RAM",
      "64 bit Windows 10 Operating System",
      "512 GB SSD",
      "39.62 cm (15 inches) Display",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/image25.jpg",
  },
  {
    id: "laptop96",
    name: "Nokia PureBook X14 Core i5 10th Gen - (8 GB/512 GB SSD/Windows 10 Home) NKi510UL85S Thin and Light Lap...",
    brand: "Nokia",
    price: 50490.0,
    ratings: 4.4,
    details: [
      "Intel Core i5 Processor (10th Gen)",
      "8 GB DDR4 RAM",
      "64 bit Windows 10 Operating System",
      "512 GB SSD",
      "35.56 cm (14 inch) Display",
      "1 Year Onsite Warranty Commencing from the Date of Purchase",
    ],
    image: "https://example.com/image26.jpg",
  },
  {
    id: "laptop97",
    name: "ASUS VivoBook 15 (2022) Core i5 11th Gen - (8 GB/1 TB HDD/256 GB SSD/Windows 10 Home) X515EA-EJ502TS T...",
    brand: "ASUS",
    price: 50990.0,
    ratings: 4.3,
    details: [
      "Intel Core i5 Processor (11th Gen)",
      "8 GB DDR4 RAM",
      "Windows 10 Operating System",
      "1 TB HDD|256 GB SSD",
      "39.62 cm (15.6 inch) Display",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/image27.jpg",
  },
  {
    id: "laptop98",
    name: "DELL Ryzen 3 Dual Core 3250U - (8 GB/512 GB SSD/Windows 11 Home) INSPIRON 3515 Thin and Light Laptop",
    brand: "DELL",
    price: 40690.0,
    ratings: 4.0,
    details: [
      "AMD Ryzen 3 Dual Core Processor",
      "8 GB DDR4 RAM",
      "64 bit Windows 11 Operating System",
      "512 GB SSD",
      "39.62 cm (15.6 inch) Display",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/image28.jpg",
  },
  {
    id: "laptop99",
    name: "DELL Core i5 11th Gen - (8 GB/512 GB SSD/Windows 11 Home) D560784WIN9S Laptop",
    brand: "DELL",
    price: 59936.0,
    ratings: 4.0,
    details: [
      "Intel Core i5 Processor (11th Gen)",
      "8 GB DDR4 RAM",
      "Windows 11 Operating System",
      "512 GB SSD",
      "39.62 cm (15.6 inch) Display",
      "1 YEAR",
    ],
    image: "https://example.com/image29.jpg",
  },
  {
    id: "laptop100",
    name: "DELL Vostro Ryzen 5 Quad Core 3500U - (8 GB/512 GB SSD/Windows 10) Vostro 3405 Thin and Light Laptop",
    brand: "DELL",
    price: 49690.0,
    ratings: 4.4,
    details: [
      "AMD Ryzen 5 Quad Core Processor",
      "8 GB DDR4 RAM",
      "64 bit Windows 10 Operating System",
      "512 GB SSD",
      "35.56 cm (14 inches) Display",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/image30.jpg",
  },
  {
    id: "laptop101",
    name: "APPLE 2021 Macbook Pro M1 Pro - (16 GB/512 GB SSD/Mac OS Monterey) MK1E3HN/A",
    brand: "APPLE",
    price: 222990.0,
    ratings: 4.8,
    details: [
      "Apple M1 Pro Processor",
      "16 GB Unified Memory RAM",
      "Mac OS Operating System",
      "512 GB SSD",
      "41.15 cm (16.2 inch) Display",
      "1 Year Limited Warranty",
    ],
    image: "https://example.com/image31.jpg",
  },
  {
    id: "laptop102",
    name: "APPLE 2022 MacBook AIR M2 - (8 GB/512 GB SSD/Mac OS Monterey) MLY03HN/A",
    brand: "APPLE",
    price: 139990.0,
    ratings: 4.3,
    details: [
      "Apple M2 Processor",
      "8 GB Unified Memory RAM",
      "Mac OS Operating System",
      "512 GB SSD",
      "34.54 cm (13.6 Inch) Display",
      "1 Year Limited Warraadnty",
    ],
    image: "https://example.com/image32.jpg",
  },
  {
    id: "laptop103",
    name: "Infinix INBook X2 Plus Core i3 11th Gen - (8 GB/512 GB SSD/Windows 11 Home) XL25 Thin and Light Laptop",
    brand: "Infinix",
    price: 31990.0,
    ratings: 4.2,
    details: [
      "Intel Core i3 Processor (11th Gen)",
      "8 GB LPDDR4X RAM",
      "64 bit Windows 11 Operating System",
      "512 GB SSD",
      "39.62 cm (15.6 Inch) Display",
      "1 Year Onsite Warranty",
    ],
    image: "https://example.com/image33.jpg",
  },
  {
    id: "laptop104",
    name: "DELL G15 Core i7 12th Gen - (16 GB/512 GB SSD/Windows 11 Home/4 GB Graphics/NVIDIA GeForce RTX 3050 Ti...",
    brand: "DELL",
    price: 111990.0,
    ratings: 4.0,
    details: [
      "Intel Core i7 Processor (12th Gen)",
      "16 GB DDR5 RAM",
      "64 bit Windows 11 Operating System",
      "512 GB SSD",
      "39.62 cm (15.6 Inch) Display",
      "1 Year Premium Support",
    ],
    image: "https://example.com/image34.jpg",
  },
  {
    id: "laptop105",
    name: "Lenovo IdeaPad 3 Core i3 11th Gen - (8 GB/256 GB SSD/Windows 11 Home) 15ITL05 Thin and Light Laptop",
    brand: "Lenovo",
    price: 35990.0,
    ratings: 4.2,
    details:
      "['Intel Core i3 Processor (11th Gen)' '8 GB DDR4 RAM' '64 bit Windows 11 Operating System' '256 GB SSD' '39.62 cm (15.6 Inch) Display' '2 Years Onsite�Warranty']",
    image: "https://example.com/image34.jpg",
  },
];
